### ISSUE TITLE
cell_id convention

### ISSUE THREAD

**Issue by alasdairrae** [ogpetrov/s2toolkit#1]
Thanks for providing this plugin, super-useful. An issue I have is that the cellid generated by the plugin does not match the format I expected when using S2 geometry in other applications - example below of a cellid for level 11

`0x487615c000000000`

Do you know if it is possible to generate cellid in the format above?

**Comment by ogpetrov** [comment]
Thanks for the feedback! We are using the Python implementation of S2 - s2sphere as a base, apparently it uses a different output format. We will look into having cellid output in the format you gave (and seems to match the original S2 documentation :) ).

**Comment by alasdairrae** [comment]
Thanks very much, that's great. If I can get s2 cells with the cell_ids just like the ones I have below (these are in London, UK) then that would be excellent.


0x47d8a04000000000
0x47d8a0c000000000
0x47d8a14000000000
0x47d8a1c000000000
0x47d8a24000000000
0x47d8a34000000000
0x47d8a44000000000

**Comment by ogpetrov** [comment]
@alasdairrae QGIS finally approved the new version of the plugin (0.3), it now automatically adds the field in the form you wanted. Also we added a few more features :)

**Comment by alasdairrae** [comment]
That's amazing, thanks so much!
